# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='dqd', max_length=16)),
            ],
        ),
    ]
